<?php

namespace ContainerLxpxbg2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovieFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\MovieFormType' shared autowired service.
     *
     * @return \App\Form\Type\MovieFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/MovieFormType.php';

        return $container->privates['App\\Form\\Type\\MovieFormType'] = new \App\Form\Type\MovieFormType();
    }
}
