<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App_Entity_Movie' => 0,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Movie',
                    'id',
                    'title',
                    'director',
                    'year',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'title' => $o[2],
                        'director' => $o[3],
                        'year' => $o[4],
                    ],
                ],
                'groups' => [
                    1 => [
                        'movie',
                    ],
                    [
                        'movie',
                    ],
                    [
                        'movie',
                    ],
                    [
                        'movie',
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
